# Generated by Django 3.2.9 on 2021-11-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='curserial_number',
            field=models.TextField(blank=True, help_text='the current nft serial number'),
        ),
    ]
