# Generated by Django 3.2.9 on 2021-11-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0004_breadpage_curserial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='datamine',
            field=models.TextField(blank=True, help_text='the location of the datamine for this piece'),
        ),
    ]
