# Generated by Django 3.2.9 on 2021-11-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0006_breadpage_contactid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadpage',
            name='contactid',
        ),
    ]
