# Generated by Django 3.2.9 on 2021-12-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('breads', '0008_breadpage_jrreditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='bookmark',
            field=models.ForeignKey(blank=True, help_text='This is the template bookmark.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
