# Generated by Django 3.2.9 on 2021-12-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0009_breadpage_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='bperbookmark',
            field=models.TextField(blank=True, help_text='number of bytes per bookmark. Warning Compete with the previous. Use one or other. '),
        ),
        migrations.AddField(
            model_name='breadpage',
            name='maxbookmarksupply',
            field=models.TextField(blank=True, help_text='number of bytes per bookmark. Warning Compete with the previous. Use one or other. '),
        ),
        migrations.AddField(
            model_name='breadpage',
            name='maxbooksupply',
            field=models.TextField(blank=True, help_text='the max number of books this smart book has'),
        ),
    ]
