# Generated by Django 3.2.9 on 2021-12-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0012_auto_20211204_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='bookmarkprice',
            field=models.TextField(blank=True, help_text='the price of a single bookmark.'),
        ),
        migrations.AddField(
            model_name='breadpage',
            name='bookprice',
            field=models.TextField(blank=True, help_text='the price of a single book.'),
        ),
        migrations.AlterField(
            model_name='breadpage',
            name='bperbookmark',
            field=models.TextField(blank=True, help_text='number of bytes per bookmark. Warning Compete with the next. Use one or other. '),
        ),
    ]
