# Generated by Django 3.2.9 on 2021-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0013_auto_20211205_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Make any additional promises to your readers here.'),
        ),
    ]
