# Generated by Django 3.2.9 on 2021-12-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0014_alter_breadpage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='usejrreditor',
            field=models.BooleanField(default=False),
        ),
    ]
