# Generated by Django 3.2.9 on 2021-12-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0015_breadpage_usejrreditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='hardbound',
            field=models.TextField(blank=True, help_text='how many hardbound books are in this smart book. -1 means infinite.'),
        ),
    ]
