# Generated by Django 3.2.9 on 2021-12-16 00:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0016_breadpage_hardbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='hardboundfrom',
            field=models.TextField(blank=True, help_text='where to start autoselling hardbounds from.'),
        ),
        migrations.AddField(
            model_name='breadpage',
            name='hardboundprice',
            field=models.TextField(blank=True, help_text='the price of a single hardbound book in MATIC.'),
        ),
        migrations.AlterField(
            model_name='breadpage',
            name='jrreditor',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
