# Generated by Django 3.2.10 on 2021-12-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0017_auto_20211216_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='authorwallet',
            field=models.CharField(blank=True, help_text='The wallet address of the author of this book.', max_length=255),
        ),
    ]
